exe_1: main.cpp
	g++ main.cpp -o main -std=c++11 -Dsubtask1

exe_2: main.cpp
	g++ main.cpp -o main -std=c++11 -Dsubtask2

exe_3: main.cpp
	g++ main.cpp -o main -std=c++11 -Dsubtask3

exe_4: main.cpp
	g++ main.cpp -o main -std=c++11 -Dsubtask4

clean:
	rm main